### ISSUE TITLE
How to detect client endpoint to push notifications?

### ISSUE THREAD

**Issue by pwFoo** [sagiegurari/simple-web-notification#3]
Hi, @sagiegurari 
I try to explain my question from issue #2, because I think your lib could fine for me if I understand how it works...

I try to send a push notification triggered by a website event to the subscribed client /endpoint. So each user / device get user specific notifications.

I found this demo with closed browser support: https://gauntface.github.io/simple-push-demo/
It shows the curl command to send a notification to a remote device which works fine with closed browser (android device).

So I need to know the registration endpoint of device to trigger a (remote) notification to it. How to detect / get the device registration with your lib?

Second question
You use FCM to push notifications. Is it possible to push notifications with a custom service-worker.js direct from my own server to the device or is a gateway / service like FCM needed?

**Comment by sagiegurari** [comment]
push notifications and device registration is not what this lib is about.
push notifications is something else and has to do with pushing info from server to device.
this library is about web notifications, meaning showing a notification to the user which you trigger manually due to any event you like (for example you got a push notification from the server and decide to show the user some info via web notification).
hope this explains a bit.

I don't use firebase at all in my examples. I don't do push notifications anywhere.

**Comment by pwFoo** [comment]
Yes, I close the issue because questions are answered. Thanks!
